#!/bin/bash

### BEGIN INIT INFO
# Provides:		attach-kiss
# Required-Start: 	$local_fs $network
# Required-Stop:	$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	attach-kiss service
# Description: 		Attaches Data Radio Kiss device
### END INIT INFO

# Author: Nino Carrillo <nino.carrillo@outlook.com>

case "$1" in
	start)
		echo "Attaching KISS Data Radio"
		sudo /usr/local/bin/attach-kiss
		;;
	stop)
		echo "Disconnecting KISS Data Radio"
		sudo killall kissattach
		;;
	*)
		echo "Usage: /etc/init.d/attach-kiss {start|stop}"
		exit 1
		;;
	esac

exit 0

